apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudapigateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudapigateway
  template:
    metadata:
      labels:
        app: cloudapigateway
    spec:
      containers:
      - name: cloudapigateway
        image: "mkdockerhub1310/msbootcampactivity_2020:cloudapigateway"
        ports:
        - containerPort: 9092