apiVersion: apps/v1
kind: Deployment
metadata:
  name: config1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config1
  template:
    metadata:
      labels:
        app: config1
    spec:
      containers:
      - name: config1
        image: "mkdockerhub1310/msbootcampactivity_2020:config1"
        ports:
        - containerPort: 8888