apiVersion: v1
kind: Service
metadata:
  name: conversionms
  labels:
    app: conversionms
spec:
  selector:
    app: conversionms
  type: NodePort 
  ports:
   - nodePort: 31005
     port: 8081
     targetPort: 8081