apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversionms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversionms
  template:
    metadata:
      labels:
        app: conversionms
    spec:
      containers:
      - name: conversionms
        image: "mkdockerhub1310/msbootcampactivity_2020:conversionms"
        ports:
        - containerPort: 8081
