apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: currencyms
        image: "mkdockerhub1310/msbootcampactivity_2020:currencyms"
---
apiVersion: v1
kind: Service
metadata:
  name: currencyms
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30001