apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyms
  template:
    metadata:
      labels:
        app: currencyms
    spec:
      containers:
      - name: currencyms
        image: "mkdockerhub1310/msbootcampactivity_2020:currencyms"
        ports:
        - containerPort: 8082
