apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka1
  template:
    metadata:
      labels:
        app: eureka1
    spec:
      containers:
      - name: eureka1
        image: "mkdockerhub1310/msbootcampactivity_2020:eureka1"
        ports:
        - containerPort: 8761