apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: eureka1
        image: "mkdockerhub1310/msbootcampactivity_2020:eureka1"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka1
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 30001
